INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Accesorios para Vehículos", "Accesorios para Vehículos");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Animales y Mascotas", "Animales y Mascotas");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Arte y Antigüedades", "Arte y Antigüedades");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Bebés", "Bebés");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Cámaras y Accesorios", "Cámaras y Accesorios");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Celulares y Telefonía", "Celulares y Telefonía");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Coleccionables", "Coleccionables");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Computación", "Computación");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Consolas y Videojuegos", "Consolas y Videojuegos");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Deportes y Fitness", "Deportes y Fitness");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Electrodomésticos y Aires Ac.", "Electrodomésticos y Aires Ac.");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Electrónica, Audio y Video", "Electrónica, Audio y Video");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Hogar, Muebles y Jardín", "Hogar, Muebles y Jardín");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Industrias y Oficinas", "Industrias y Oficinas");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Instrumentos Musicales", "Instrumentos Musicales");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Joyas y Relojes", "Joyas y Relojes");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Juegos y Juguetes", "Juegos y Juguetes");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Música, Libros y Películas", "Música, Libros y Películas");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Ropa, Calzados y Accesorios", "Ropa, Calzados y Accesorios");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Salud y Belleza", "Salud y Belleza");
INSERT INTO CATEGORIAS (nombre, descripcion) VALUES ("Otras categorías", "Otras categorías");
